import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import styles from '../styles/Home.module.css'
import { initializeApp } from "firebase/app";
//import { getAnalytics } from "firebase/analytics";
// https://firebase.google.com/docs/web/setup#available-libraries

// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: "AIzaSyD9VmjEPRgJ6vgEoO-HaDRyrZG6KPNORwc",
  authDomain: "nodiumapp.firebaseapp.com",
  projectId: "nodiumapp",
  storageBucket: "nodiumapp.appspot.com",
  messagingSenderId: "75670864673",
  appId: "1:75670864673:web:fc11770492730128d57460",
  measurementId: "G-RTST9YPPMD"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
import { getAuth, createUserWithEmailAndPassword } from "firebase/auth";
const auth = getAuth(app);
let stream = "";

function login(email, password) {
  signInWithEmailAndPassword(auth, email, password)
  .then((userCredential) => {
    // Signed in 
    const user = userCredential.user;
    // ...
  })
  .catch((error) => {
    const errorCode = error.code;
    const errorMessage = error.message;
  });
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <nav>
      <Image src="./stadia.svg" alt="Stadia Logo" />
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nodiumapp.github.io">Nodium!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
      </main>
      <main style={{visibility: 'hidden'}}>
        <div id="video">
          <video controls muted>
            <source src={stream}></source>
          </video>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/nodiumapp/nodium"
          target="_blank"
          rel="noopener noreferrer"
        >
          See the code here
        </a>
        <p>{' '}</p>
        <a
          href="https://vercel.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Hosted by{' '}
          <span className={styles.logo}>
            <Image src="./vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
          !
        </a>
      </footer>
    </div>
  )
}
